// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJLP5NvmRIGosY5ynKKhXQ9e46BaiZ89w',
    appId: '1:644078765192:web:5ee053b37e779f60ca8b3d',
    messagingSenderId: '644078765192',
    projectId: 'mindlink-fe376',
    authDomain: 'mindlink-fe376.firebaseapp.com',
    storageBucket: 'mindlink-fe376.appspot.com',
    measurementId: 'G-9T9GPTLHHM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB84xBClkNDp0X5rlwoF6GcXZFdvL4ULyI',
    appId: '1:644078765192:android:5b9c1f59f6b41dbbca8b3d',
    messagingSenderId: '644078765192',
    projectId: 'mindlink-fe376',
    storageBucket: 'mindlink-fe376.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCA7jtpAslVB_GReX63YmmjBFjo_2CwylU',
    appId: '1:644078765192:ios:8628c919544f1291ca8b3d',
    messagingSenderId: '644078765192',
    projectId: 'mindlink-fe376',
    storageBucket: 'mindlink-fe376.appspot.com',
    iosBundleId: 'com.example.mindlink',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCJLP5NvmRIGosY5ynKKhXQ9e46BaiZ89w',
    appId: '1:644078765192:web:b3259640a0bc5468ca8b3d',
    messagingSenderId: '644078765192',
    projectId: 'mindlink-fe376',
    authDomain: 'mindlink-fe376.firebaseapp.com',
    storageBucket: 'mindlink-fe376.appspot.com',
    measurementId: 'G-40V0Q626NG',
  );
}
